# Generated by Django 4.2.30 on 2026-05-11 20:03

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_booking_ref_and_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(default=bookings.models.generate_booking_ref, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('received', 'Received'), ('washing', 'Washing'), ('rinsing', 'Rinsing'), ('drying', 'Drying'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
