# Generated by Django 4.2.30 on 2026-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_add_image_to_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
