# Generated by Django 4.2.30 on 2026-05-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('momo', 'MTN MoMo'), ('airtel', 'Airtel Money'), ('cash', 'Cash')], default='momo', max_length=10),
        ),
    ]
